name: health_care_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  # A
  auto_route: ^9.2.2
  another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  cached_network_image:
  # D
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  fl_chart: ^0.69.0
  ficonsax: ^0.0.3
  flex_color_scheme: ^7.3.1
  flutter_gen: ^5.7.0
  flutter_mobx: ^2.0.6+5
  # G
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  # H
  http: ^0.13.5
  # I
  injectable:
  intl: any
  # J
  json_annotation: ^4.9.0
  json_serializable: ^6.6.1
  # K
  # L
  logger: ^2.4.0
  # M
  toastification: ^2.3.0
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.0.14
  # Q
  # R
  retrofit: ^4.4.1

  # S
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  # T
  tuple: ^2.0.2
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  flutter_localizations:
    sdk: flutter
  # Y
  # Z

dev_dependencies:
  build_runner:
  retrofit_generator: ">=8.0.0 <10.0.0"
  injectable_generator:
  auto_route_generator:
  flutter_gen_runner:
  mobx_codegen: ^2.2.0
  analyzer:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/src/core/theme/
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    png: true
    svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
