name: health_care_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  # A
  another_flushbar: ^1.12.29
  # B
  # C
  cupertino_icons: ^1.0.5
  # D
  dio: ^5.1.1
  # E
  event_bus: ^2.0.0
  # F
  flex_color_scheme: ^7.3.1
  flutter_gen: ^5.7.0
  flutter_mobx: ^2.0.6+5
  # G
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  # H
  http: ^0.13.5
  # I
  intl: ^0.19.0
  # J
  json_serializable: ^6.6.1
  # K
  # L
  # M
  mobx: ^2.1.4
  # N
  # O
  # P
  path_provider: ^2.0.14
  # Q
  # R
  # S
  shared_preferences: ^2.1.0
  sembast_web: ^2.1.3
  sembast: ^3.4.4
  # T
  # U
  # V
  validators: ^3.0.0
  # W
  # X
  xxtea: ^2.1.0
  # Y
  # Z

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  mobx_codegen: ^2.2.0
  analyzer: ^5.10.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/src/core/theme/

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    png: true
    svg: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
