import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:health_care_app/src/core/responsive/app_responsive.dart';

class AppFont {
  TextTheme fontTheme(
    BuildContext context, {
    Color? color,
    FontWeight? weight = FontWeight.w400,
    FontStyle? style,
    Color? backgroundColor,
    Paint? background,
    double? height,
    double? letterSpacing,
  }) =>
      TextTheme(
        // * display
        displayLarge: GoogleFonts.lato(
          fontSize: context.sizeHeight(50),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        displayMedium: GoogleFonts.lato(
          fontSize: context.sizeHeight(44),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        displaySmall: GoogleFonts.lato(
          fontSize: context.sizeHeight(40),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        // * headline
        headlineLarge: GoogleFonts.lato(
          fontSize: context.sizeHeight(34),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        headlineMedium: GoogleFonts.lato(
          fontSize: context.sizeHeight(32),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          height: height,
          background: background,
          letterSpacing: letterSpacing,
        ),
        headlineSmall: GoogleFonts.lato(
          fontSize: context.sizeHeight(30),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        // * title
        titleLarge: GoogleFonts.lato(
          fontSize: context.sizeHeight(28),
          fontWeight: weight,
          color: color,
          backgroundColor: backgroundColor,
          fontStyle: style,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        titleMedium: GoogleFonts.lato(
          fontSize: context.sizeHeight(26),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          letterSpacing: letterSpacing,
          height: height,
        ),
        titleSmall: GoogleFonts.lato(
          fontSize: context.sizeHeight(24),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          letterSpacing: letterSpacing,
          height: height,
        ),

        // * label
        labelLarge: GoogleFonts.lato(
          fontSize: context.sizeHeight(22),
          fontWeight: weight,
          color: color,
          backgroundColor: backgroundColor,
          fontStyle: style,
          background: background,
          height: height,
          letterSpacing: letterSpacing,
        ),
        labelMedium: GoogleFonts.lato(
          fontSize: context.sizeHeight(20),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          background: background,
          letterSpacing: letterSpacing,
          height: height,
        ),
        labelSmall: GoogleFonts.lato(
          fontSize: context.sizeHeight(18),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          background: background,
          backgroundColor: backgroundColor,
          letterSpacing: letterSpacing,
          height: height,
        ),

        // * body
        bodyLarge: GoogleFonts.lato(
          fontSize: context.sizeHeight(16),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          background: background,
          letterSpacing: letterSpacing,
          height: height,
          backgroundColor: backgroundColor,
        ),
        bodyMedium: GoogleFonts.lato(
          fontSize: context.sizeHeight(14),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          backgroundColor: backgroundColor,
          letterSpacing: letterSpacing,
          height: height,
          background: background,
        ),
        bodySmall: GoogleFonts.lato(
          fontSize: context.sizeHeight(12),
          fontWeight: weight,
          color: color,
          fontStyle: style,
          height: height,
          background: background,
          letterSpacing: letterSpacing,
          backgroundColor: backgroundColor,
        ),
      );
}
